# Site settings
title: Lindsay & John Get Married
email: webmaster@lindsayandjohngetmarried.com
description: > # this means to ignore newlines until "baseurl:"
  Lindsay West & John Bunselmeyer Get Married!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lindsayandjohngetmarried.com" # the base hostname & protocol for your site
cdn: ""
twitter_username: wmluke
github_username:  wmluke

# Build settings
markdown: kramdown
sass:
    style: :compressed
